name: fqsha
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - fiona
  - gdal[version='>=3.6,<3.9']
  - sqlite
  - gmt=6
  - numpy[version='<2']
  - pip
  - pip:
      - alpha-shapes==1.1.1
      - asgiref==3.11.0
      - cftime==1.6.5
      - django==4.2.27
      - docutils==0.22.4
      - h5py==3.15.1
      - llvmlite==0.46.0
      - netcdf4==1.7.4
      - numba==0.63.1
      - numpy==1.24.4
      - openquake-engine==3.23.0
      - -e .
      - pandas==2.3.3
      - pygmt==0.13.0
      - pyproj==3.7.1
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.18
      - pyqt5-sip==12.17.2
      - pytz==2025.2
      - shapely==2.1.2
      - sqlparse==0.5.5
      - toml==0.10.2
      - tzdata==2025.3
      - xarray==2025.6.1
prefix: /home/geo/anaconda3/envs/fqsha
